#!/usr/bin/env ruby
# frozen_string_literal: false

require 'English'

status = 0
ARGV.each do |file|
  output = `puppet epp validate "#{file}" 2>&1`
  next if $CHILD_STATUS.exitstatus.zero

  puts "#{file}: failed epp validation"
  puts output
  status = 1
end

exit status
